#!/usr/bin/env python3
"""RAGAS tables and figure of the paper (writes into paper/generated and paper/figs).

    ragas_crag.tex     CRAG, every method with the common reader (gpt-5-nano) and RAGAS judge; contexts at
                       <=500-character granularity (Search-R1/BM25 single blocks re-split). Delta: paired
                       difference vs MA-Chunk-P (lambda=0.4), Wilcoxon per question, Holm within the baseline family.
    ragas_effect.tex   precision-aware reward vs v3 at a matched chunk budget, per dataset (Holm across datasets),
                       and the selection ceiling (oracle - v3).
    figs/ragas_frontier.pdf   RAGAS-5 vs chunks sent, per dataset.

Sources: results/v4/ragas/<dataset>/*.parquet (see docs/PROTOCOL.md).
Usage: python scripts/paper/tables_ragas.py
"""
import re
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd
from scipy import stats

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from ma_chunk.config import DATA, REPO, RESULTS  # noqa: E402
REPO_ROOT = REPO
R = RESULTS / "v4/ragas"
GEN = REPO / "paper/generated"
FIGS = REPO / "paper/figs"
M = ["faithfulness", "answer_relevancy", "answer_correctness", "context_precision", "context_recall"]
P = "ma_msg_rw-marginal_ap_to-confidence"  # MA-Chunk-P: precision-aware reward + confidence order
MATCHED = {"crag": ("0.4", "1.25"), "hotpotqa": ("0.3", "1.0"), "musique": ("0.3", "1.0")}
INK, MUTED, GRID = "#1f1f1e", "#6b6b66", "#e6e5e0"


def per_question(ds):
    df = pd.concat([pd.read_parquet(p) for p in (R / ds).glob("*.parquet")], ignore_index=True)
    df["method"] = df["condition"].str.replace(r"_s\d+$", "", regex=True)
    df["ragas5"] = df[M].mean(axis=1, skipna=True)
    q = df.groupby(["method", "interaction_id"])[M + ["ragas5", "n_contexts"]].mean()
    return q


def holm(p):
    p = np.asarray(p, float); order = np.argsort(p); adj = np.empty(len(p)); run = 0.0
    for k, i in enumerate(order):
        run = max(run, min(1.0, (len(p) - k) * p[i])); adj[i] = run
    return adj


def paired(a, b, k):
    common = a.index.intersection(b.index)
    d = (a.loc[common, k] - b.loc[common, k]).dropna().to_numpy()
    nz = d[d != 0]
    return d.mean(), (stats.wilcoxon(nz).pvalue if len(nz) > 1 else 1.0), len(d)


def boot(x, rng, n=2000):
    x = x[~np.isnan(x)]
    b = [x[rng.integers(0, len(x), len(x))].mean() for _ in range(n)]
    return np.percentile(b, 2.5), np.percentile(b, 97.5)


def f3(x):
    return f"{x:.3f}".replace("-", "$-$")


def table_crag():
    q = per_question("crag")
    ref = q.loc[f"{P}_lam0.4"]
    groups = [
        ("Retrieval baselines", [("paper_bm25_chunked", "BM25$^{\\dagger}$"), ("paper_faiss", "FAISS"),
                                 ("paper_colbert", "ColBERTv2"), ("paper_dr_faiss", "DeepRetrieval+FAISS"),
                                 ("paper_dr_bm25", "DeepRetrieval+BM25"), ("paper_searchr1_chunked", "Search-R1$^{\\dagger}$")]),
        ("Prior single-agent RL", [("rl_ppo", "PPO"), ("rl_recurrent_ppo", "R-PPO"), ("rl_ddpg", "DDPG"), ("rl_sac", "SAC")]),
        ("Same pool", [("topk_ce_3", "Cross-enc.\\ top-3"), ("rrf_3", "RRF top-3"), ("single_lam0.6", "Single, $\\lambda$=0.6")]),
        ("\\method{}", [("ma_msg_lam0.3", "MA+msg, $\\lambda$=0.3"), ("ma_msg_lam1.0", "MA+msg, $\\lambda$=1"),
                        (f"{P}_lam0.4", "MA-Chunk-P, $\\lambda$=0.4"), (f"{P}_lam1.25", "MA-Chunk-P, $\\lambda$=1.25")]),
        ("Upper bound", [("oracle", "Oracle (useful chunk)")]),
    ]
    tests = {}
    fam = [m for _, rows in groups for m, _ in rows if m != f"{P}_lam0.4"]
    raw = {m: paired(q.loc[m], ref, "ragas5") for m in fam}
    adj = dict(zip(fam, holm([raw[m][1] for m in fam])))
    rng = np.random.default_rng(0)
    lines = ["% AUTO-GENERATED by scripts/paper/tables_ragas.py",
             "\\begin{table*}[t]", "\\centering\\small",
             "\\caption{RAGAS on CRAG with a common reader and judge (\\texttt{gpt-5-nano}); every context list at the "
             "same granularity ($\\le$500 characters). Learned methods: 3 seeds averaged per question. RAGAS-5: mean of the five "
             "metrics (95\\% bootstrap CI). $\\Delta$: paired difference to MA-Chunk-P ($\\lambda$=0.4) on common questions; "
             "$^{*}$: $p_{\\mathrm{Holm}}<0.05$ (Wilcoxon, Holm over the rows). $^{\\dagger}$Delivered as one $\\approx$5{,}000-character "
             "block, re-split for evaluation; as a single block their context precision reads 0.54 (BM25) and 0.52 (Search-R1).}",
             "\\label{tab:ragas-crag}", "\\setlength{\\tabcolsep}{3.5pt}",
             "\\begin{tabular}{ll r ccccc c r}", "\\toprule",
             "Group & Method & Chunks & Faith. & Ans.\\ rel. & Ans.\\ corr. & Ctx.\\ prec. & Ctx.\\ rec. & RAGAS-5 [95\\% CI] & $\\Delta$ \\\\",
             "\\midrule"]
    for gname, rows in groups:
        for i, (m, label) in enumerate(rows):
            x = q.loc[m]
            lo, hi = boot(x["ragas5"].to_numpy(float), rng)
            if m == f"{P}_lam0.4":
                delta = "ref."
            else:
                d, _, _ = raw[m]
                delta = f3(d) + ("$^{*}$" if adj[m] < 0.05 else "")
            cells = [f"{x[k].mean():.3f}" for k in M]
            lead = f"\\multirow{{{len(rows)}}}{{*}}{{{gname}}}" if i == 0 else ""
            name = f"\\textbf{{{label}}}" if m == f"{P}_lam0.4" else label
            lines.append(f"{lead} & {name} & {x['n_contexts'].mean():.1f} & " + " & ".join(cells) +
                         f" & {x['ragas5'].mean():.3f} [{lo:.3f}, {hi:.3f}] & {delta} \\\\")
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\end{table*}"]
    (GEN / "ragas_crag.tex").write_text("\n".join(lines) + "\n")
    return {m: (raw[m][0], adj[m]) for m in fam}


def table_effect():
    rows, praw = [], {"context_precision": [], "ragas5": [], "context_recall": []}
    data = {}
    for ds, (l1, l2) in MATCHED.items():
        q = per_question(ds)
        v3 = pd.concat([q.loc["ma_msg_lam0.3"], q.loc["ma_msg_lam1.0"]]).groupby(level=0).mean()
        pv = pd.concat([q.loc[f"{P}_lam{l1}"], q.loc[f"{P}_lam{l2}"]]).groupby(level=0).mean()
        ch_v3 = (q.loc["ma_msg_lam0.3"]["n_contexts"].mean() + q.loc["ma_msg_lam1.0"]["n_contexts"].mean()) / 2
        ch_p = (q.loc[f"{P}_lam{l1}"]["n_contexts"].mean() + q.loc[f"{P}_lam{l2}"]["n_contexts"].mean()) / 2
        res = {k: paired(pv, v3, k) for k in praw}
        for k in praw:
            praw[k].append(res[k][1])
        oracle = q.loc["oracle"]["ragas5"].mean() - q.loc["ma_msg_lam0.3"]["ragas5"].mean()
        data[ds] = dict(lams=f"{l1}/{l2}", ch_v3=ch_v3, ch_p=ch_p, res=res, oracle=oracle)
    adj = {k: holm(v) for k, v in praw.items()}
    names = {"crag": "CRAG", "hotpotqa": "HotpotQA", "musique": "MuSiQue"}
    lines = ["% AUTO-GENERATED by scripts/paper/tables_ragas.py",
             "\\begin{table}[t]", "\\centering\\footnotesize",
             "\\caption{Precision-aware reward (MA-Chunk-P) vs.\\ MA+msg at a matched chunk budget ($\\lambda$ chosen on "
             "chunk counts only, before any LLM evaluation). Paired differences per question (3 seeds, two budgets averaged), "
             "Wilcoxon with Holm across datasets ($p$ in parentheses). Ceiling: RAGAS-5 of the oracle minus MA+msg ($\\lambda$=0.3).}",
             "\\label{tab:ragas-effect}", "\\setlength{\\tabcolsep}{2.5pt}",
             "\\begin{tabular}{l c c c c c}", "\\toprule",
             " & Chunks & $\\Delta$ Ctx.\\ prec. & $\\Delta$ Ctx.\\ rec. & $\\Delta$ RAGAS-5 & Ceiling \\\\", "\\midrule"]
    for i, (ds, d) in enumerate(data.items()):
        cells = []
        for k in ["context_precision", "context_recall", "ragas5"]:
            diff = d["res"][k][0]
            p = adj[k][i]
            ptxt = "$<$0.001" if p < 0.001 else f"{p:.3f}"
            cells.append(f"{f3(diff)} ({ptxt})")
        lines.append(f"{names[ds]} & {d['ch_v3']:.2f}$\\to${d['ch_p']:.2f} & " + " & ".join(cells) + f" & $+${d['oracle']:.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (GEN / "ragas_effect.tex").write_text("\n".join(lines) + "\n")
    return data, adj


def figure():
    panels = {"crag": "CRAG", "hotpotqa": "HotpotQA (300)", "musique": "MuSiQue (300)"}
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.5))
    for ax, (ds, title) in zip(axes, panels.items()):
        q = per_question(ds)
        s = q.groupby(level=0)[["ragas5", "n_contexts"]].mean()

        def pt(m):
            return s.loc[m, "n_contexts"], s.loc[m, "ragas5"]

        if ds == "crag":
            for m, lab in [("paper_colbert", "ColBERTv2"), ("paper_searchr1_chunked", "Search-R1"),
                           ("paper_dr_faiss", "DR+FAISS"), ("paper_bm25_chunked", "BM25"), ("paper_dr_bm25", "DR+BM25"),
                           ("paper_faiss", "FAISS")]:
                x, y = pt(m)
                ax.scatter(x, y, color="#8a8a85", s=14, marker="s", zorder=2, label="Retrieval baselines" if m == "paper_colbert" else None)
                off = {"DR+FAISS": (-3, -7), "DR+BM25": (-3, -7)}.get(lab, (-3, 3))
                ax.annotate(lab, (x, y), textcoords="offset points", xytext=off, fontsize=5.5, color=MUTED, ha="right")
            for m in ["rl_ppo", "rl_recurrent_ppo", "rl_ddpg", "rl_sac"]:
                x, y = pt(m)
                ax.scatter(x, y, color="#c4b8e8", s=12, marker="v", zorder=2, label="Prior single-agent RL" if m == "rl_ppo" else None)
        stat = [m for m in ["topk_ce_1", "topk_ce_2", "topk_ce_3", "rrf_3"] if m in s.index]
        for m in stat:
            x, y = pt(m)
            ax.scatter(x, y, color="#4a3aa7", s=14, marker="D", zorder=3, label="Static (same pool)" if m == stat[0] else None)
        v3 = [m for m in ["ma_msg_lam1.0", "ma_msg_lam0.3"] if m in s.index]
        ax.plot(*zip(*[pt(m) for m in v3]), color="#2a78d6", marker="o", ms=4, lw=1.6, zorder=4, label="MA+msg (v3)")
        lp = [f"{P}_lam{l}" for l in ["1.25", "1.0", "0.4", "0.3"] if f"{P}_lam{l}" in s.index]
        lp = sorted(lp, key=lambda m: s.loc[m, "n_contexts"])
        ax.plot(*zip(*[pt(m) for m in lp]), color="#1baf7a", marker="o", ms=4, lw=1.6, zorder=5, label="MA-Chunk-P (v4)")
        x, y = pt("oracle")
        ax.scatter(x, y, color="#eb6834", marker="*", s=70, zorder=6, label="Oracle")
        for sp in ("top", "right"):
            ax.spines[sp].set_visible(False)
        for sp in ("left", "bottom"):
            ax.spines[sp].set_color(MUTED)
        ax.tick_params(colors=MUTED, labelsize=7)
        ax.grid(True, color=GRID, lw=0.6)
        ax.set_axisbelow(True)
        ax.set_title(title, fontsize=9, color=INK)
        ax.set_xlabel("chunks sent to the reader", fontsize=7, color=MUTED)
    axes[0].set_ylabel("RAGAS-5", fontsize=7, color=MUTED)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=6, frameon=False, fontsize=6.5, bbox_to_anchor=(0.5, -0.02))
    fig.tight_layout(rect=(0, 0.1, 1, 1))
    FIGS.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGS / "ragas_frontier.pdf")
    fig.savefig(FIGS / "ragas_frontier.png", dpi=170)
    plt.close(fig)


def main():
    GEN.mkdir(parents=True, exist_ok=True)
    t = table_crag()
    for m, (d, p) in sorted(t.items(), key=lambda kv: kv[1][1]):
        print(f"{m:55s} delta {d:+.4f} p_holm {p:.4f}")
    data, adj = table_effect()
    for i, (ds, d) in enumerate(data.items()):
        print(ds, d["lams"], f"chunks {d['ch_v3']:.2f}->{d['ch_p']:.2f}",
              {k: (round(v[0], 4), round(float(adj[k][i]), 4)) for k, v in d["res"].items()}, f"ceiling {d['oracle']:+.3f}")
    figure()
    print("wrote", GEN / "ragas_crag.tex", GEN / "ragas_effect.tex", FIGS / "ragas_frontier.pdf")


if __name__ == "__main__":
    main()
