#!/usr/bin/env python3
"""Generates the data-driven LaTeX tables of the paper (v3) into paper/generated/:

    validation_conservative.tex  pre-specified comparisons, cluster-level (dataset x seed) tests
    algorithms_validation.tex    MA+msg trained with PPO / A2C / DQN / Recurrent PPO (3 seeds)
    sustainability.tex           CodeCarbon energy/CO2 and wall time of every component

Inputs: results/validation/analysis/{conservative_tests.csv, all_runs.csv},
        results/sustainability/costs.jsonl.
Usage (from the repo root):  python scripts/paper/tables_validation.py
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

from ma_chunk.config import DATA, REPO, RESULTS  # noqa: E402
REPO_ROOT = REPO
A = RESULTS / "validation" / "analysis"
GEN = REPO / "paper" / "generated"
DS = {"crag": "CRAG", "hotpotqa": "HotpotQA", "musique": "MuSiQue"}
ALGOS = {"ppo": ("ma_msg", "PPO"), "a2c": ("ma_msg_algo-a2c", "A2C"), "dqn": ("ma_msg_algo-dqn", "DQN"),
         "recurrent_ppo": ("ma_msg_algo-recurrent_ppo", "R-PPO")}


def num(x, d=3):
    return f"{x:.{d}f}".replace("-", "$-$")


def p_fmt(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def conservative():
    t = pd.read_csv(A / "conservative_tests.csv")
    label = {
        ("ma_msg", "single"): "MA+msg vs.\\ Single",
        ("ma_msg_rich", "single_rich"): "MA+msg-rich vs.\\ Single-rich",
        ("ma_msg", "ma"): "MA+msg vs.\\ MA (no messages)",
        ("ma_msg", "ma_msg_rw-terminal"): "marginal vs.\\ terminal reward",
        ("ma_msg", "ma_msg_rw-individual"): "marginal vs.\\ selfish reward",
        ("ma_msg", "ma_msg_to-random"): "round-robin vs.\\ random order",
        ("ma_msg", "ma_msg_to-confidence"): "round-robin vs.\\ confidence order",
        ("ma_msg", "ma_msg_rand"): "5 agents vs.\\ +random agent",
        ("ma_msg", "ma_msg_m4"): "top-8 vs.\\ top-4 lists",
        ("ma_msg", "ma_msg_m12"): "top-8 vs.\\ top-12 lists",
        ("ma_msg", "ma_msg_drop0.2"): "standard vs.\\ failure-aware (clean)",
        ("ma_msg", "sup_gbm_obsfeat"): "MA+msg vs.\\ supervised (parity)",
        ("ma_msg", "sup_gbm"): "MA+msg vs.\\ supervised GBM (rich)",
        ("ma_msg", "sup_logreg"): "MA+msg vs.\\ supervised logistic (rich)",
        ("ma_msg_rich", "sup_gbm"): "MA+msg-rich vs.\\ supervised GBM (rich)",
        ("ma_msg_rich", "sup_logreg"): "MA+msg-rich vs.\\ supervised logistic (rich)",
    }
    fam = {"decomposition": "Decomposition", "reward": "Reward and credit", "orchestration": "Orchestration",
           "robustness": "Robustness and sensitivity", "why_rl": "Why RL?"}

    def k(x):  # differences in units of 1e-3 team reward (keeps the column narrow, avoids "-0.000")
        return num(1000 * x, 1)

    lines = ["% AUTO-GENERATED by scripts/paper/tables_validation.py",
             "\\begin{table}[t]", "\\centering\\footnotesize",
             "\\caption{Pre-specified comparisons at the cluster level (dataset $\\times$ seed; team reward averaged "
             "over $\\lambda\\in\\{0.3,1\\}$). $\\Delta$: mean paired difference $A-B$ in units of $10^{-3}$ team reward, "
             "with 95\\% cluster-bootstrap CI; W/L: clusters won/lost by $A$; exact Wilcoxon signed-rank $p$, "
             "Holm-corrected within each family.}",
             "\\label{tab:validation}", "\\setlength{\\tabcolsep}{2.5pt}",
             "\\begin{tabular}{l r c r}", "\\toprule",
             "$A$ vs.\\ $B$ & $\\Delta$ [95\\% CI] & W/L & $p_{\\mathrm{Holm}}$ \\\\", "\\midrule"]
    for i, (f, g) in enumerate(t.groupby("family", sort=False)):
        if i:
            lines.append("\\addlinespace[2pt]")
        lines.append(f"\\multicolumn{{4}}{{l}}{{\\emph{{{fam[f]}}}}} \\\\")
        for r in g.itertuples():
            name = label.get((r.a, r.b), f"{r.a} vs. {r.b}")
            mark = "$^{\\dagger}$" if getattr(r, "ci_method", "bootstrap") == "range" else ""
            diff = f"{k(r.mean_diff)} [{k(r.ci_lo)}, {k(r.ci_hi)}]{mark}"
            lines.append(f"\\quad {name} & {diff} & {r.wins}/{r.losses} & {p_fmt(r.p_holm)} \\\\")
    lines += ["\\bottomrule",
              "\\multicolumn{4}{p{0.97\\columnwidth}}{\\scriptsize $^{\\dagger}$CRAG only, where utility saturates "
              "(3 clusters; range over clusters instead of CI). On the 6 multi-hop clusters both rewards produced "
              "identical policies, as Proposition~\\ref{prop:modular} predicts.}",
              "\\end{tabular}", "\\end{table}"]
    (GEN / "validation_conservative.tex").write_text("\n".join(lines) + "\n")


def algorithms():
    """Per-algorithm table. Inference is cluster-level as in the main comparisons: team reward averaged
    over lambda inside each (dataset, seed) cluster; Friedman test over the four algorithms and exact
    Wilcoxon of PPO vs. each other algorithm (Holm), on the clusters where all four are complete."""
    from scipy import stats as sst
    runs = pd.read_csv(A / "all_runs.csv")
    runs = runs.sort_values("source", ascending=False).drop_duplicates(["dataset", "variant", "lam", "seed"])
    runs = runs[runs["seed"].isin([0, 1, 2])]
    costs = [json.loads(l) for l in (RESULTS / "sustainability/costs.jsonl").read_text().splitlines()]
    minutes = {(c["dataset"], c["algo"]): c["train_seconds"] / 60 for c in costs
               if c["mode"] == "train" and c["variant"] == "ma_msg"}
    stats = {}
    for algo, (variant, _) in ALGOS.items():
        for ds in DS:
            for lam in (0.3, 1.0):
                x = runs[(runs.dataset == ds) & (runs.variant == variant) & np.isclose(runs.lam, lam)]["team_reward"]
                stats[(algo, ds, lam)] = (x.mean(), x.std(), len(x)) if len(x) else (np.nan, np.nan, 0)
    best = {(ds, lam): np.nanmax([stats[(a, ds, lam)][0] for a in ALGOS]) for ds in DS for lam in (0.3, 1.0)}

    # cluster matrix: rows (dataset, seed), columns algorithms
    sub = runs[runs.variant.isin([v for v, _ in ALGOS.values()]) & runs.lam.isin([0.3, 1.0])]
    cnt = sub.groupby(["dataset", "seed", "variant"]).size().unstack()
    clu = sub.groupby(["dataset", "seed", "variant"])["team_reward"].mean().unstack()
    clu = clu[(cnt == 2).reindex(columns=clu.columns).fillna(False)]
    clu = clu.reindex(columns=[v for v, _ in ALGOS.values()]).dropna()
    n_cl = len(clu)
    rank, fried_p, pair = {}, np.nan, {}
    if n_cl >= 2:
        r = clu.rank(axis=1, ascending=False)
        rank = r.mean().to_dict()
        fried_p = sst.friedmanchisquare(*[clu[c] for c in clu.columns]).pvalue
        raw = {}
        for v in clu.columns[1:]:
            d = (clu["ma_msg"] - clu[v]).to_numpy()
            nz = d[d != 0]
            raw[v] = (int((d > 0).sum()), int((d < 0).sum()), sst.wilcoxon(nz, method="exact").pvalue if len(nz) >= 2 else 1.0)
        order = sorted(raw, key=lambda v: raw[v][2])
        run = 0.0
        for i, v in enumerate(order):
            run = max(run, min(1.0, (len(order) - i) * raw[v][2]))
            pair[v] = (raw[v][0], raw[v][1], run)
    fried = f"Friedman $p={fried_p:.3f}$" if np.isfinite(fried_p) else "Friedman test pending"
    if np.isfinite(fried_p) and fried_p < 0.001:
        fried = "Friedman $p<0.001$"
    lines = ["% AUTO-GENERATED by scripts/paper/tables_validation.py",
             "\\begin{table*}[t]", "\\centering\\small",
             "\\caption{MA-Chunk (MA+msg) trained with four RL algorithms (identical environment, network and budget). "
             "Test team reward, 5-fold CV, mean $\\pm$ sd over 3 seeds. Rank: mean rank over the "
             f"{n_cl} (dataset, seed) clusters (team reward averaged over $\\lambda$; {fried}). vs.\\ PPO: clusters won/lost "
             "by PPO and exact Wilcoxon $p$ (Holm). Minutes: wall time of one five-fold training run on one CPU core "
             "(CRAG / HotpotQA / MuSiQue). Best mean per column in bold.}",
             "\\label{tab:algorithms}", "\\setlength{\\tabcolsep}{3.5pt}",
             "\\begin{tabular}{l cc cc cc c c c}", "\\toprule",
             " & \\multicolumn{2}{c}{CRAG} & \\multicolumn{2}{c}{HotpotQA} & \\multicolumn{2}{c}{MuSiQue} & & & \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
             "Algorithm & $\\lambda$=0.3 & $\\lambda$=1 & $\\lambda$=0.3 & $\\lambda$=1 & $\\lambda$=0.3 & $\\lambda$=1 "
             "& Rank & vs.\\ PPO & Minutes \\\\",
             "\\midrule"]
    for algo, (variant, name) in ALGOS.items():
        cells = []
        for ds in DS:
            for lam in (0.3, 1.0):
                m, sd, n = stats[(algo, ds, lam)]
                if n == 0:
                    c = "--"
                else:
                    c = num(m) + (f"$\\pm${sd:.3f}" if n >= 2 else "") + ("" if n >= 3 else f"$^{{n={n}}}$")
                    if np.isclose(m, best[(ds, lam)]):
                        c = f"\\textbf{{{c}}}"
                cells.append(c)
        rk = f"{rank[variant]:.2f}" if variant in rank else "--"
        vs = "--" if variant == "ma_msg" or variant not in pair else \
            f"{pair[variant][0]}/{pair[variant][1]}, {p_fmt(pair[variant][2])}"
        mins = "/".join(f"{minutes[(ds, algo)]:.0f}" if (ds, algo) in minutes else "--" for ds in DS)
        lines.append(f"{name} & " + " & ".join(cells) + f" & {rk} & {vs} & {mins} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (GEN / "algorithms_validation.tex").write_text("\n".join(lines) + "\n")
    print("algorithms: clusters", n_cl, "rank", {k: round(v, 2) for k, v in rank.items()}, "friedman", fried_p, "pairs", pair)
    return stats


def sustainability():
    c = pd.DataFrame([json.loads(l) for l in (RESULTS / "sustainability/costs.jsonl").read_text().splitlines()])
    tr = c[c["mode"] == "train"].set_index(["dataset", "variant", "algo"])
    sup = c[c["mode"] == "sup"].set_index("dataset")
    sc = c[c["mode"] == "scoring"].set_index("dataset")

    def cell(ds, f):
        try:
            return f(ds)
        except KeyError:
            return "--"

    co2 = c["carbon_intensity_kg_per_kwh"].dropna().iloc[0] * 1000
    rows = [
        ("\\multicolumn{4}{l}{\\emph{Training: 5 folds $\\times$ 200k steps, 1 CPU core}} \\\\", None),
        ("MA+msg, PPO (min / Wh)",
         lambda d: f"{tr.loc[(d, 'ma_msg', 'ppo'), 'train_seconds'] / 60:.0f} / {1000 * tr.loc[(d, 'ma_msg', 'ppo'), 'train_energy_kwh']:.1f}"),
        ("\\quad A2C / DQN / R-PPO (Wh)",
         lambda d: "/".join(f"{1000 * tr.loc[(d, 'ma_msg', a), 'train_energy_kwh']:.1f}" for a in ("a2c", "dqn", "recurrent_ppo"))),
        ("Single, PPO (Wh)", lambda d: f"{1000 * tr.loc[(d, 'single', 'ppo'), 'train_energy_kwh']:.1f}"),
        ("Supervised GBM fit (Wh)", lambda d: f"{1000 * sup.loc[d, 'train_energy_kwh']:.3f}"),
        ("\\midrule\\multicolumn{4}{l}{\\emph{Inference, per question}} \\\\", None),
        ("Policy, PPO (ms / $\\mu$Wh)",
         lambda d: f"{1000 * tr.loc[(d, 'ma_msg', 'ppo'), 'infer_seconds_per_query']:.1f} / {1e9 * tr.loc[(d, 'ma_msg', 'ppo'), 'infer_energy_kwh_per_query']:.0f}"),
        ("Supervised GBM (ms / $\\mu$Wh)",
         lambda d: f"{1000 * sup.loc[d, 'infer_seconds_per_query']:.1f} / {1e9 * sup.loc[d, 'infer_energy_kwh_per_query']:.0f}"),
        ("Cand.\\ scoring, GPU$^{\\ddagger}$ (s / mWh)",
         lambda d: f"{sc.loc[d, 'seconds_per_query']:.2f} / {1e6 * sc.loc[d, 'energy_kwh_per_query']:.0f}"),
    ]
    lines = ["% AUTO-GENERATED by scripts/paper/tables_validation.py",
             "\\begin{table}[t]", "\\centering\\footnotesize",
             "\\caption{Computational cost measured with CodeCarbon (process mode). CPU-only jobs: CPU and RAM energy; "
             f"emissions follow from the local grid intensity ({co2:.0f}\\,g CO$_2$/kWh, e.g.\\ 4\\,Wh $\\approx$ 0.4\\,g). "
             "No component calls an LLM. $^{\\ddagger}$Upper bound (shared GPU). Candidates per question: "
             "$\\approx$1{,}450 (CRAG), 10 (HotpotQA), 20 (MuSiQue).}",
             "\\label{tab:sustainability}", "\\setlength{\\tabcolsep}{2.5pt}",
             "\\begin{tabular}{l ccc}", "\\toprule", " & CRAG & HotpotQA & MuSiQue \\\\", "\\midrule"]
    for label, f in rows:
        if f is None:
            lines.append(label)
        else:
            lines.append(f"{label} & " + " & ".join(cell(d, f) for d in DS) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (GEN / "sustainability.tex").write_text("\n".join(lines) + "\n")


def main():
    GEN.mkdir(parents=True, exist_ok=True)
    conservative()
    st = algorithms()
    sustainability()
    for k, v in st.items():
        print(k, tuple(round(x, 4) if isinstance(x, float) else x for x in v))


if __name__ == "__main__":
    main()
